#!/bin/bash

#if [ $# -lt 2 ]
#then
#    echo "Nombre d'arguments invalides"
#    echo "Utilisation :"
#    echo "./jlc -s fileName"
#    echo "./jlc -b JVM fileName"
#    echo "./jlc -b LLVM fileName"
#fi

if [ $# == 1 ]
then
    lib/jlc -b JVM $1
    str="$1"
    fileName=${str/%jl/j}
    java -jar lib/jasmin.jar $fileName
fi

if [ $1 == "-b" ]
then
    if [ $2 == "JVM" ]
    then
	lib/jlc $1 $2 $3
	str="$3"
	fileName=${str/%jl/j}
	java -jar lib/jasmin.jar $fileName
    else
	if [ $2 == "LLVM" ]
	then
	    lib/jlc $1 $2 $3
	    str="$3"
	    fileName=${str/%jl/ll}
	    llvm-as $fileName
	    fileAs=${fileName/%ll/bc}
	    fileOpt=${fileName/%.ll/Opt.bc}
	    opt -std-compile-opt $fileAs > $FileOpt
	    #llvm-ld fileAs lib/runtime.bc
            llvm-ld $FileOpt lib/runtime.bc
	else
	    echo "x86 generation not implemented"
	fi
    fi
else
    lib/jlc $1 $2
fi